### ISSUE TITLE
Not initializing flatfile correctly

### ISSUE THREAD

**Issue by GiantCowFilms** [brendanashworth/flatfile#2]
It appears that if there is no flat file, or the file is empty, it will cause this module to crash. To fix this the flat file needs to be initialized with an empty object in it, which is annoying. The fix seems like it would be very very very simple.

**Comment by brendanashworth** [comment]
@GiantCowFilms thanks for opening an issue. I'll work on this.

**Comment by brendanashworth** [comment]
@GiantCowFilms this has been fixed in https://github.com/brendanashworth/flatfile/commit/7e559b05d41c198e4dbff317c11d50ae26cae4b5, a semver-major release will come soon.
