### ISSUE TITLE
Advantages?

### ISSUE THREAD

**Issue by rolfen** [brendanashworth/flatfile#3]
What would I gain by using flatfile? I could just do JSON.parse() on a file myself.
The reason why I don't, and look around github instead, is that I'm concerned about scalability and performance when loading all the data every time.
If flatfile really brings something, compared to native JSON.parse(), then I think you should mention it in the readme.

**Comment by brendanashworth** [comment]
@rolfen thanks for opening an issue. You definitely could do `JSON.parse()` on the file yourself. Right now, this library won't bring anything new to the table in regards to scalability or performance, it's more just providing an abstraction for it. It means that it'll be unit tested and maintained independently, but that's really up to your mindset with regards to small modules about whether or not you should use it.
